name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    # strategy:
    #   fail-fast: false
    # matrix:
    #   containers: [1, 2] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          # start: npm start
          #! I need to add a file where I create a server???
          # start: npm run cypress:run
          # wait-on: 'http://localhost:3000' # Waits for above
          # wait-on: 'http://[::1]:3000' # Waits for above
          # wait-on: 'http://127.0.0.1:3000' # Waits for above
          # Records to Cypress Cloud
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          #! browser: chrome
          record: true
          # parallel: true # Runs test in parallel using settings above
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
